travis:
  secure:
    BINSTAR_TOKEN: Vnrswpi+4Eg/qbkf7UQEqYX53m2uRD/SkeX/PF05i8VEv10VmyTkuGvIewqIA7y/uP9SuSRKGs1hGkpnkmIbuLM2pEdFg/W8mQJa4zSmtnPMKRr0yPdYg0PC7V4SGnN33ZryToKK/rHhPCrXfRkLxQ39/4VjEud0CZN4TJMwy81xMdaer6ZR6rTn0hgrGhfMlgkoVhBj+UwFtQAA4pvCXmESSsTWAIcOGVhhbbQref4QfyaoN3e7zD88sHGpyVl2MnjAjeAhzgtTvWxQxqigh9T5FT10EJZ+0mXGPIYSrx4txW14U+8aDObW+b/hiU0u8HQeDZ38vtgqRXh7yWiRppTppaie5EyA81qSgIhnLE+rCTKp34ehKy/o9qyTom9rYQsQWzUr06JNBMyMCP8Siu2d46MUgMRfsSExT1QW/a0XJK6TUYP9wuvhQN4vNm29Tav9hjlvvgHBc400Bc/vmOuCs6Mf2bZvj2J96KUiFrR+epDZjOA8hB+8bR/W1AdQ29tNqTIg1H6259G1RIFtmlHOt2rI6FZ4DyjYTMVM3IpZmlsAx5xYXmCwD0QLUdN9wJd/Pylw7ps+JWnjC74mnQxzIBmPjgjQh5/TvI7m6QG8A2VG8eHKRTHCfllFz42QaBbwCTRK5V47aZbLkpuLr90Cwi8DWes0blOEiYSgpl8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
